### PR TITLE
STONK-2: Frontend > Add Linting Rules

### PR DESCRIPTION
**Pull request by one2code**
## Ticket

https://github.com/JackyTea/Mock-Stocks-Collaborative/issues/3

## Changes

Installed ESLint as a dev dependency in the frontend directory, and then configured the settings with an eslintrc.json file. My reasoning for choosing to configure via the eslintrc.json is that this seems to be the industry standard way of configuring ESLint in the OSS community, based on evaluating other large OSS projects. Therefore, I thought it would be better to maintain the eslintrc.json method of configuration.

## Developer Checklist

- [x] I have verified my changes to confirm that it works
- [x] I have added the appropriate label to this pull request
- [x] I have linked the corresponding issue to this pull request
- [x] I have followed the pull request title pattern of `STONK-NUMBER: Domain > Issue Title`

### CODE REVIEW

**Comment by one2code** [comment]
I began work on the backend ESLint configuration and discovered some other good linting rules to add to the frontend, I will be updating this PR very shortly with those ESLint rules. I'll edit this post after the update has been completed.

**Review by JackyTea — APPROVED** [review]

**Comment by JackyTea** [comment]
Changed from package managers pnpm to npm, so package-lock is removed.

**Comment by one2code** [comment]
I'll review the merge conflicts and resolve them in VSCode tonight in the Merge Conflict editor.

**Comment by one2code** [comment]
Ok, looks like the pnpm migration was merged first, creating a conflict on the package-lock.json file. I'm going to delete all of the node modules and re-install everything with pnpm, and that should clear up the merge conflicts.

**Review by JackyTea — APPROVED** [review]

**Pull request merged**
