### PR TITLE
STONK-3: Backend > Add Linting Rules

### PR DESCRIPTION
**Pull request by one2code**
## Ticket

https://github.com/JackyTea/Mock-Stocks-Collaborative/issues/4

## Changes

Installed ESLint as a dev dependency in the Backend directory, along with @typescript-eslint/parser @typescript-eslint/eslint-plugin. ESLint configuration was performed in a `.eslintrc.js` to maintain consistency in the project. React specific lint rules were removed and replaced with Node specific lint rules, including the Node recommended rules, and additional lint rules surrounding asynchronous functions.

## Developer Checklist

- [x] I have verified my changes to confirm that it works
- [x] I have added the appropriate label to this pull request
- [x] I have linked the corresponding issue to this pull request
- [x] I have followed the pull request title pattern of `STONK-NUMBER: Domain > Issue Title`

### CODE REVIEW

**Review by JackyTea — DISMISSED** [review]

**Comment by JackyTea** [comment]
Changed from package managers pnpm to npm, so package-lock is removed.

**Comment by one2code** [comment]
I'll review the merge conflicts and resolve them in VSCode tonight in the Merge Conflict editor.

**Comment by one2code** [comment]
Looks like the pnpm migration was merged first, creating merge conflicts with my feature branches on merge. I've resolved the merge conflicts and re-installed all of the required ESLint dependencies via pnpm package-lock.json file. After review, it should be good to merge.

**Comment by one2code** [comment]
Alright, everything should be good to go. Merge conflicts are resolved, and should be good to merge after review.

**Review by JackyTea — APPROVED** [review]

**Pull request merged**
